### ISSUE TITLE
useScroll 无法识别 window 上的滚动

### ISSUE THREAD

**Issue by lizy0329** [umijs/hooks#190]
源码中：
```
element.addEventListener('scroll', listener);

setPosition({
    left: event.target.scrollLeft,
    top: event.target.scrollTop
 });
```
都是只接受一个 dom 的局部滚动，无法兼容全局滚动。

是有意为之还是说不考虑全局滚动？

**Comment by awmleer** [comment]
传 `document` 就可以了：

```
useScroll(document)
```

**Comment by lizy0329** [comment]
> 传 `document` 就可以了：
> 
> ```
> useScroll(document)
> ```

不可以，event.target.scrollTop 是 undefined

**Comment by awmleer** [comment]
> > 传 `document` 就可以了：
> > ```
> > useScroll(document)
> > ```
> 
> 不可以，event.target.scrollTop 是 undefined

的确是。。我修复一下
