### ISSUE TITLE
useAPI 默认不会带上Cookie且没有暴露Cookie配置接口

### ISSUE THREAD

**Issue by lizy0329** [umijs/hooks#211]
由于 useAPI 默认采用了 fetch 实现，但 fetch 默认不带 Cookie，这就导致了业务方无法识别登录态，同时，也没有暴露 credentials 接口配置

**Comment by tli4** [comment]
使用 configRequest 可以传入自己封装过后，加过 credentials，错误处理，或者一些自定义 header 的 fetch. 全局生效。

https://github.com/umijs/hooks/blob/1f5b5db165bd2c381e4698d31c0f10c8f455bb6f/src/useAPI/index.ts#L15


参考这个[例子](https://hooks.umijs.org/zh-cn/useAPI#%E4%BF%AE%E6%94%B9-request-%E6%96%B9%E6%B3%95)也可以给单独使某个 useAPI 使用自定义的方法。

**Comment by lizy0329** [comment]
道理都懂，我甚至可以用 useAsync，但为啥我要用 useAPI，不就是贪图有内置 request 方便么？

**Comment by songchengen** [comment]
虽然可以自己基于useAsync封装一个自己的useAPI，实现也很easy，但是现在的useAPI感觉更像一个useAsync的封装demo，不是那么精美好用

**Comment by brickspert** [comment]
我们现在在开发 新的 useAPI，大家莫着急~ 好用的快来了。

**Comment by lizy0329** [comment]
新的 useAPI 能够媲美 useSWR 吗？如果不能，那就封装一下 swr 好了＾０＾~

**Comment by brickspert** [comment]
@lizy0329 个人感觉应该比 swr 更“产品化”，应该不会太差~   目前正在开发ing

**Comment by brickspert** [comment]
最新版 v1.6.0 发布了 [useRequest](https://hooks.umijs.org/zh-CN/async)
