### ISSUE TITLE
useInViewport 不能监控多个 dom

### ISSUE THREAD

**Issue by lizy0329** [umijs/hooks#243]
const [ inViewPort, ref? ] = useInViewport(dom);
这种用法能监控多个 dom 是否在 viewport 里么？

**Comment by brickspert** [comment]
目前不支持这个特性呢~

**Comment by lizy0329** [comment]
> 目前不支持这个特性呢~

有相关计划支持么？不然这个 hooks 就不实用了

**Comment by brickspert** [comment]
在什么场景下会有这种需求呢？

**Comment by brickspert** [comment]
先关了哈，如果确实有场景需求，我们会加上~

**Comment by lizy0329** [comment]
> 在什么场景下会有这种需求呢？

这种场景很多吧，比如：
1. 列表条目需要曝光上传到BI
2. 列表条目如果在 viewport 中就变色什么的，让用户清楚
