### ISSUE TITLE
useRequest - 加载更多模式的一些疑问

### ISSUE THREAD

**Issue by lizy0329** [umijs/hooks#291]
result 永远是 undefined，而且没有分页模式那种自动管理 current 页数，那到底要怎样分页？自己额外计算？

而且，加载模式好像也是遗漏了在 body 上滚动的设定

```
const { data, loading, loadMore, loadingMore } = useRequest(
        (result) => ({
            url: `${config.baseHost}/api/comment/getListByPage`,
            method: 'get',
            params: {
                content_id: getQueryString('id'),
                page: `${result}`,
                perpage: 3
            }
        }),
        {
            loadMore: true,
            formatResult: response => {
                if (response.code == 0) {
                    return {
                        list: response.data.list,
                        total: response.data.total
                    };
                }
            }
        }
    );
```

**Comment by brickspert** [comment]
1. useRequest 的 loadMore 模式没有管理分页了，需要自己额外计算。你可以根据返回结果计算。类似例子中的 offset 计算。
result 是你接口的返回结果。当然第一次没请求之前肯定是 result。

2. 在 body 上滚动这个确实是问题。我支持下哈。

**Comment by lizy0329** [comment]
> 1. useRequest 的 loadMore 模式没有管理分页了，需要自己额外计算。你可以根据返回结果计算。类似例子中的 offset 计算。
>    result 是你接口的返回结果。当然第一次没请求之前肯定是 result。
> 2. 在 body 上滚动这个确实是问题。我支持下哈。

1. 这个就很奇怪了，当我看到分页模式时，是有分页管理的，理所应当地以为加载更多模式也同样有，我看了半个小时，怎么都找不到，后来用了1个小时调试，才知道好像没有分页管理。

2. 在针对 body 这个维度上，很多个 Hook 都是欠考虑的，滚动操作是重灾区，刚出来时往往只考虑局部

**Comment by brickspert** [comment]
> > 1. useRequest 的 loadMore 模式没有管理分页了，需要自己额外计算。你可以根据返回结果计算。类似例子中的 offset 计算。
> >    result 是你接口的返回结果。当然第一次没请求之前肯定是 result。
> > 2. 在 body 上滚动这个确实是问题。我支持下哈。
> 
> 1. 这个就很奇怪了，当我看到分页模式时，是有分页管理的，理所应当地以为加载更多模式也同样有，我看了半个小时，怎么都找不到，后来用了1个小时调试，才知道好像没有分页管理。
> 2. 在针对 body 这个维度上，很多个 Hook 都是欠考虑的，滚动操作是重灾区，刚出来时往往只考虑局部

关于为什么加载更多模式不管理分页的解释：
加载模式太灵活了，我们需要支持较多的场景。
如果你的数据一直在更新，那你不能通过分页来读取到正确的下一页数据，你可能需要类似 startId、offset、nextId 这一类数据。比如加载更多第一个例子，是通过 nextId 来控制下一页的。
当然如果你的数据不会更新，那你通过分页能拿到正确的数据。当然此时你可以通过自己的 result 计算得到自己当前的页数，这样 useRequest 就不用对数据结构做约束了，用户自己决定。

**Comment by lizy0329** [comment]
谢谢解惑！但可以期待下有个默认模式

**Comment by noxxxxxxxx** [comment]
> 1. useRequest 的 loadMore 模式没有管理分页了，需要自己额外计算。你可以根据返回结果计算。类似例子中的 offset 计算。
>    result 是你接口的返回结果。当然第一次没请求之前肯定是 result。
> 2. 在 body 上滚动这个确实是问题。我支持下哈。

请问 body 滚动这个问题有支持了么
